version: "3.8"
services:


  test:
    container_name: visium_delivery
    build:
      context: ../
      dockerfile: deployments/visium_delivery/Dockerfile
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - "/oui:/test"

    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
