version: "3.8"
services:


  test:
    container_name: test
    build:
      context: ../
      dockerfile: deployments/test/Dockerfile
    ports:
      - "5000:5000"
      - "8888:8888"

    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
